name: 'Scout Test'

on: 
  push:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/scout/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/scout
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test