name: CI


on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: apps/scout

jobs:
  'show-structure':
    runs-on: ubuntu-latest
    steps:
      - run: cp ../ | ls -al
      - run: cp ../guinea-pig-nestjs | ls -al
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test